// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sweSeqGwOvwkVfCBtvWuhEzzBo8z4gM',
    appId: '1:841946131371:web:251d8c8c6ad28be52140ee',
    messagingSenderId: '841946131371',
    projectId: 'sscrm-a2ea4',
    authDomain: 'sscrm-a2ea4.firebaseapp.com',
    storageBucket: 'sscrm-a2ea4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqZG85BkpFnRltz8ELqO-tK8YkFHwsM4',
    appId: '1:841946131371:android:6383adc994a47db22140ee',
    messagingSenderId: '841946131371',
    projectId: 'sscrm-a2ea4',
    storageBucket: 'sscrm-a2ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsZqvJZJo2iXI9C6uIv9Yl-80Dm1SXfxI',
    appId: '1:841946131371:ios:b69e0658820af8722140ee',
    messagingSenderId: '841946131371',
    projectId: 'sscrm-a2ea4',
    storageBucket: 'sscrm-a2ea4.firebasestorage.app',
    iosBundleId: 'com.example.ssApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsZqvJZJo2iXI9C6uIv9Yl-80Dm1SXfxI',
    appId: '1:841946131371:ios:b69e0658820af8722140ee',
    messagingSenderId: '841946131371',
    projectId: 'sscrm-a2ea4',
    storageBucket: 'sscrm-a2ea4.firebasestorage.app',
    iosBundleId: 'com.example.ssApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2sweSeqGwOvwkVfCBtvWuhEzzBo8z4gM',
    appId: '1:841946131371:web:51d34ebb3ec8f41b2140ee',
    messagingSenderId: '841946131371',
    projectId: 'sscrm-a2ea4',
    authDomain: 'sscrm-a2ea4.firebaseapp.com',
    storageBucket: 'sscrm-a2ea4.firebasestorage.app',
  );
}
